import type { Metadata } from "next";
import { MedievalSharp } from 'next/font/google';
import "./globals.css";

const magicFont = MedievalSharp({
  weight: '400',
  subsets: ['latin'],
  variable: '--font-magic',
});

export const metadata: Metadata = {
  title: "Magic Animation",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${magicFont.variable} font-magic`}>
        {children}
      </body>
    </html>
  );
}
